package com.flipfit.business;

import java.util.*;
import com.flipfit.bean.*;
import com.flipfit.dao.GymUserDAO;
import com.flipfit.dao.GymUserDAOImpl;

public class GymUserService {
    private GymUserDAO gymUserDAO = new GymUserDAOImpl();

    // Constructor
    public GymUserService() {
        System.out.println("✅ GymUserService initialized with Database DAO");
    }

    public boolean registerUser(User user) {
        // Check if email already exists
        if (gymUserDAO.getUserByEmail(user.getEmail()) != null) {
            System.out.println("❌ Email already registered!");
            return false;
        }

        boolean success = gymUserDAO.registerUser(user);
        if (success) {
            System.out.println("✅ User registered successfully!");
            // Note: UserId is generated by DB. If needed, we fetch the user back.
        } else {
            System.out.println("❌ Registration failed!");
        }
        return success;
    }

    public User login(String email, String password) {
        User user = new User();
        user.setEmail(email);
        user.setPassword(password);

        if (gymUserDAO.authenticateUser(user)) {
            return gymUserDAO.getUserByEmail(email);
        }
        return null;
    }

    public void logout(int userId) {
        // No session management needing database update usually, unless we track active
        // sessions
        System.out.println("✅ Logged out successfully!");
    }

    public User getUserById(int userId) {
        return gymUserDAO.getUserById(userId);
    }

    public User getUserByEmail(String email) {
        return gymUserDAO.getUserByEmail(email);
    }

    public boolean updateUserProfile(User user) {
        if (gymUserDAO.getUserById(user.getUserId()) == null) {
            System.out.println("❌ User not found!");
            return false;
        }

        boolean success = gymUserDAO.updateUserProfile(user);
        if (success) {
            System.out.println("✅ Profile updated successfully!");
        }
        return success;
    }

    public boolean deleteUser(int userId) {
        if (gymUserDAO.getUserById(userId) == null) {
            System.out.println("❌ User not found!");
            return false;
        }
        boolean success = gymUserDAO.deleteUser(userId);
        if (success) {
            System.out.println("✅ User deleted successfully!");
        }
        return success;
    }

    public boolean changePassword(int userId, String oldPassword, String newPassword) {
        User user = gymUserDAO.getUserById(userId);

        if (user == null) {
            System.out.println("❌ User not found!");
            return false;
        }

        if (!user.getPassword().equals(oldPassword)) {
            System.out.println("❌ Old password is incorrect!");
            return false;
        }

        boolean success = gymUserDAO.changePassword(userId, newPassword);
        if (success) {
            System.out.println("✅ Password changed successfully!");
        }
        return success;
    }

    public boolean resetPassword(String email) {
        User user = gymUserDAO.getUserByEmail(email);

        if (user == null) {
            System.out.println("❌ Email not found!");
            return false;
        }

        // Generate random password (simplified)
        String newPassword = "reset" + System.currentTimeMillis() % 10000;

        // Update password in DB
        boolean success = gymUserDAO.changePassword(user.getUserId(), newPassword);

        if (success) {
            System.out.println("✅ Password reset!");
            System.out.println("   New password: " + newPassword);
            return true;
        }
        return false;
    }

    public List<User> getAllUsers() {
        return gymUserDAO.getAllUsers();
    }

    public List<User> getUsersByRole(int roleId) {
        return gymUserDAO.getUsersByRole(roleId);
    }

    public boolean activateUser(int userId) {
        // Schema limitation: No isActive column in User table currently.
        // Assuming implementation in future or using Registration approval.
        // For now, returning true as placeholder or we could update a status if added.
        System.out.println("⚠️ Activate user not fully supported in DB schema yet.");
        return true;
    }

    public boolean deactivateUser(int userId) {
        System.out.println("⚠️ Deactivate user not fully supported in DB schema yet.");
        return true;
    }
}